# Byteshade PT - Item PBR Properties

# Tools - metallic
item.0.roughness=0.3
item.0.metallic=1.0
item.1.roughness=0.3
item.1.metallic=1.0
item.2.roughness=0.3
item.2.metallic=1.0

# Bow
item.3.roughness=0.8
item.3.specular=0.0

# Fishing rod
item.4.roughness=0.9
item.4.specular=0.0

# Food
item.5.roughness=0.9
item.5.specular=0.0
